import type { Palestrante, Palestra, Patrocinador } from "./types";

export const EVENTO = {
  nome: "CITEC 2026",
  subtitulo: "Congresso de Inovação, Tecnologia e Construção Civil",
  tema: "Da sala de aula ao mercado de trabalho",
  dataInicio: "2026-06-11T15:00:00-03:00",
  dataFim: "2026-06-13T16:00:00-03:00",
  local: "Auditório Afya Uninovafapi — Teresina, PI",
  cidade: "Teresina, PI",
  // Perfil oficial do evento (usado na sala de jogos e no rodape)
  nomeOficial: "Engenharia Civil Afya Uninovafapi",
  instagramOficial: "eng.uninovafapi",
};

export const palestrantes: Palestrante[] = [
  { id: "p-renan-gomes", nome: "Renan Gomes", cargo: "Afya Teresina", bio: "Engenheiro Civil e de Segurança do Trabalho, Mestre em Engenharia de Materiais e especialista em Auditoria, Perícia Ambiental e Saneamento. Com 10 anos de docência no ensino superior, é coordenador do curso de Engenharia Civil na Afya Uninovafapi e Conselheiro do Crea-PI. Na gestão pública, atuou como Chefe de Engenharia e hoje é Assessor da SEMPLAN Teresina, liderando a gestão, fiscalização e projetos de grandes obras de infraestrutura urbana. Unindo a liderança institucional à sólida bagagem acadêmica, alia a experiência prática técnica à visão estratégica do desenvolvimento urbano.", foto: "/speakers/199948.jpg" },
  { id: "p-wallison-medeiros", nome: "Wallison Medeiros", cargo: "UFPI", bio: "Engenheiro Civil, Doutor em Estruturas e Geotecnia pela UFSCar e Professor do Departamento de Estruturas da Universidade Federal do Piauí (UFPI). Com sólida experiência profissional como projetista e consultor técnico em edificações, desenvolve pesquisas com ênfase em Alvenaria Estrutural, Concreto Armado e análise estrutural, além de integrar o Comitê Brasileiro da ABNT e assinar diversos livros e artigos científicos na área. Unindo a bagagem da engenharia consultiva à produção acadêmica de ponta, alia a experiência prática do mercado à vanguarda do desenvolvimento das normas técnicas nacionais.", foto: "/speakers/199985.jpg" },
  { id: "p-igor-veras", nome: "Igor Veras", cargo: "Construtora Belvedere", bio: "Engenheiro Civil com 8 anos de formação e especialista em Infraestrutura de Transportes, Gestão de Obras e cursando Segurança do Trabalho. Empresário há 11 anos, é sócio-administrador da Construtora Belvedere, empresa com atuação consolidada em obras e serviços públicos no Piauí. Apaixonado por tecnologia e gestão, alia a experiência prática do canteiro de obras à visão estratégica do negócio.", foto: "/speakers/199949.jpg" },
  { id: "p-itamo-miguel", nome: "Ítamo Miguel", cargo: "SDU Leste", bio: "Engenheiro Civil, Mestre em Avaliações e Valorações, e especialista em Estruturas, Fundações e Unidades Armazenadoras de Grãos. Com sólida atuação no setor público e privado, exerce a função de Gerente de Obras da SDU Leste e atua de forma independente como Calculista Estrutural, Perito e Avaliador de Imóveis. Aliando rigor acadêmico à prática de mercado, entrega soluções de alta complexidade em engenharia diagnóstica, projetos e gestão urbana.", foto: "/speakers/199950.jpg" },
  { id: "p-pedro-marques", nome: "Pedro Marques", cargo: "CREA-PI", bio: "Engenheiro Civil, Presidente em exercício no CREA-PI, Servidor público do Serviço Geológico Brasileiro - SGB/CPRM, Especialista em Construção Civil, Professor de Pós-Graduação, Perito no Instituto Brasileiro de Avaliações e Perícias - IBAPE/PI e sócio-proprietário da empresa Inspectum Engenharia, especializada em Inspeções, Avaliações e Perícias.", foto: "/speakers/199965.jpg" },
  { id: "p-alisson-dias", nome: "Alisson Dias", cargo: "Inspectum", bio: "Engenheiro Civil e Professor Universitário, Especialista em Avaliações e Perícias, Mestre em Estruturas e Construção Civil e Doutorando em Ciência dos Materiais. Membro da Associação Brasileira de Patologia das Construções e sócio-proprietário da empresa Inspectum Engenharia, especializada em Inspeções, Avaliações e Perícias.", foto: "/speakers/199967.jpg" },
  { id: "p-joao-macedo", nome: "João Macedo", cargo: "SEFAZ/PI", bio: "Engenheiro Civil, Mestre em Desenvolvimento e Meio Ambiente; Experiência na docência do ensino superior; Palestrante, consultor e instrutor na área de Licitações de Obras e Serviços de Engenharia; Auditor Governamental da SEFAZ/PI. Atualmente ocupa o Cargo de Diretor de Estruturação de Projetos, na Superintendência de Parcerias e Concessões do Estado do Piauí (SUPARC/SEAD-PI).", foto: "/speakers/199968.jpg" },
  { id: "p-julio-marques", nome: "Júlio Marques", cargo: "Secretaria de Inteligência Artificial, Economia Digital, Ciência e Tecnologia - Governo do Piauí", bio: "Doutorando em Ciência da Computação na Universidade Federal do Piauí. Possui experiência na área de Ciência da Computação, com ênfase em Processamento Digital de Imagens, Inteligência Artificial e Visão Computacional. Focado na pesquisa e no desenvolvimento tecnológico, alia o conhecimento acadêmico à aplicação prática dessas tecnologias.", foto: "/speakers/199981.jpg" },
  { id: "p-leopoldo-melo", nome: "Leopoldo Melo", cargo: "MM Locações", bio: "Engenheiro Mecânico e Engenheiro de Segurança do Trabalho. Atua no mercado empresarial como sócio da MM Locações e exerce forte liderança institucional como Presidente da APIEST (Associação Piauiense dos Engenheiros de Segurança do Trabalho). Alinhando a expertise técnica em engenharia e segurança à veia empreendedora, alia a experiência prática de gestão à representatividade da categoria no Piauí.", foto: "/speakers/199982.jpg" },
  { id: "p-paulo-roberto", nome: "Paulo Roberto", cargo: "CTS", bio: "Engenheiro Civil especializado em BIM, com pós-graduação pela PUC Minas e Master em BIM Management em andamento pela Zigurat. Senior BIM Engineer na CTS, empresa americana referência em Virtual Construction e BIM aplicado à construção. Atua com modelagem e coordenação de projetos MEP, com foco em Data Centers.", foto: "/speakers/199983.jpg" },
  { id: "p-joao-ibiapino", nome: "João Ibiapino", cargo: "JCI Engenharia", bio: "Engenheiro Civil, empresário e CEO da JCI Engenharia, empresa especializada em gestão, planejamento e execução de obras. Com experiência em empreendimentos residenciais, comerciais, corporativos e públicos, atua na liderança de projetos que unem qualidade, eficiência e controle de resultados. Sua missão é contribuir para a profissionalização do setor da construção civil, promovendo inovação, produtividade e excelência na entrega de obras.", foto: "/speakers/199984.jpg" },
  { id: "p-emmanuel-fonseca", nome: "Emmanuel Fonseca", cargo: "Obratech", bio: "Engenheiro Civil graduado pela Universidade Federal do Piauí (UFPI) e especialista com MBA em Plataforma BIM pelo INBEC. No cenário empresarial, atua como sócio-proprietário da Construtora Obratech, onde lidera a execução de projetos e serviços no setor da construção. Alinhando a bagagem técnica à vanguarda da tecnologia aplicada, alia a experiência prática da engenharia à visão estratégica e inovadora do negócio.", foto: "/speakers/199986.jpg" },
  { id: "p-jorge-cerqueira", nome: "Jorge Cerqueira", cargo: "CREA-PI", bio: "Profissional com vasta experiência em gestão de obras e especialista em engenharia de custos, atuando há mais de 15 anos no desenvolvimento de orçamentos de alta precisão. Consultor, palestrante e professor, traz em seu portfólio a participação em grandes projetos de engenharia no Piauí, além da marca de mais de 2.500 profissionais de engenharia e arquitetura capacitados por todo o Brasil. Unindo a autoridade técnica ao seu consolidado papel como educador, alia a experiência prática de mercado à visão estratégica do controle financeiro na construção.", foto: "/speakers/199987.jpg" },
  { id: "p-fabrizio-feitosa", nome: "Fabrizio Feitosa", cargo: "H3 Engenharia", bio: "Engenheiro Civil graduado pela UFPI, com mais de 11 anos de experiência e especialista em Gerenciamento de Obras e Plataforma BIM. No âmbito corporativo, atua como CEO da H3 Engenharia, liderando projetos estruturantes nos setores público e privado do Piauí, Maranhão e Paraíba, além de acumular sólida bagagem na gestão pública em cargos de confiança como gerente de obras no DER e Diretor de Engenharia no IDEPI. Unindo a liderança executiva à forte atuação institucional, alia a experiência prática do canteiro à visão estratégica de grandes obras de infraestrutura.", foto: "/speakers/199988.jpg" },
  { id: "p-fabricio-barros", nome: "Fabrício Barros", cargo: "Cap Engenharia", bio: "Orçamentista e gerente de projetos de engenharia. Desde 2013, atua como CEO da Cap Engenharia, liderando o sucesso contínuo de uma empresa especializada em fundações profundas, estacas escavadas, galpões industriais, drenagem, reformas e locação de caminhões munck. Unindo a precisão técnica da engenharia de custos à liderança executiva, alia a experiência prática do canteiro de obras à visão estratégica do negócio.", foto: "/speakers/199990.jpg" },
  { id: "p-joefton-trindade", nome: "Joefton Trindade", cargo: "Gestora Zenith", bio: "Técnico em Edificações pelo IFMA e Engenheiro Civil graduado pela UEMA. Com sólida experiência de mercado, atuou por dois anos na Estrada de Ferro Carajás (EFC/Vale) e traz em seu portfólio a execução de mais de 10 mil m² de área construída como gerenciador de obras de médio e alto padrão. No cenário empresarial, atua como sócio-proprietário da Gestora Zenith, onde une a alta precisão técnica da engenharia à gestão estratégica de projetos e negócios.", foto: "/speakers/199993.jpg" },
  { id: "p-andrei-benicio", nome: "Andrei Benicio", cargo: "OEA Engenharia", bio: "Gerente de planejamento da OEA Engenharia. Mestre em Estruturas e Construção Civil pela Universidade Federal do Ceará, possui graduação em Engenharia Civil pela Universidade Estadual do Piauí (2023). Tem experiência na área de Construção Civil, atuando principalmente nos seguintes temas: planejamento, gerenciamento e controle de obras e serviços, além da aplicação e uso de IA nos processos da construção civil.", foto: "/speakers/199995.jpg" },
  { id: "p-mikelly-martins", nome: "Mikelly Martins", cargo: "Construtora MRV", bio: "Engenheira Civil formada há 3 anos pela UNINASSAU, especialista em Patologia das Construções. Atua na área da construção civil há 5 anos e atualmente exerce a função de Engenheira Civil na MRV, desenvolvendo experiência em gestão de obras e execução.", foto: "/speakers/199997.jpg" },
  { id: "p-jose-hamilton", nome: "José Hamilton", cargo: "SDU Centro", bio: "Arquiteto e Urbanista, Doutor em Desenvolvimento e Meio Ambiente pela Universidade Federal do Piauí (UFPI) e Mestre em Arquitetura e Urbanismo pela Universidade Federal de Santa Catarina (UFSC). Atualmente, é professor no Centro Universitário Uninovafapi e integra o corpo técnico da Prefeitura Municipal de Teresina, atuando na SDU Centro. Sua atuação como pesquisador é focada na área de habitação social e assentamentos precários. Anteriormente, foi docente no curso de Arquitetura e Urbanismo da UFPI (2017-2019).", foto: "/speakers/200036.jpg" },
  { id: "p-patricia-nogueira", nome: "Patrícia Nogueira", cargo: "Afya Teresina", bio: "Mestra em Educação (UNICAMP) e graduada em Processamento de Dados, com diversas especializações nas áreas de Tecnologia, Educação e Gestão. Atualmente, integra a Diretoria de Tecnologia e Inteligência de Dados da SEGOV e atua como docente na Estácio Teresina, UNINOVAFAPI e Escola do Legislativo (ALEPI). Possui ampla experiência na coordenação e gestão do ensino superior, atuando como pesquisadora e orientadora com ênfase em Ciência da Computação, Educação a Distância (EaD) e Tecnologia.", foto: "/speakers/200072.jpg" },
  { id: "p-matheus-barbosa", nome: "Matheus Barbosa", cargo: "Topofly Engenharia", bio: "Engenheiro Agrimensor e Cartógrafo, especialista em Mapeamento Aéreo com Drones e CEO da Topofly Engenharia. Com olhar voltado para o futuro das geotecnologias, é pós-graduando em Inteligência Artificial com ênfase em negócios e inovação. Atualmente, também atua como Vice-presidente da Associação Piauiense dos Engenheiros Agrimensores e Cartógrafos, trabalhando pelo fortalecimento e representatividade do setor.", foto: "/speakers/200094.jpg" },
];

export const palestras: Palestra[] = [
  {
    id: "t422736",
    slug: "credenciamento-e-sala-de-jogos",
    titulo: "Credenciamento e Sala de Jogos",
    descricao: "Bem-vindos ao CITEC 2026! (Check-in e Credenciamento) O ponto de partida para a nossa imersão em construção e tecnologia! Chegue a partir das 15h no Auditório Afya para retirar sua credencial, garantir seu kit do evento e já iniciar o networking com outros participantes e profissionais da área antes da cerimônia de abertura.",
    palestranteId: null,
    sala: "Auditório Afya",
    inicio: "2026-06-11T15:00:00-03:00",
    fim: "2026-06-11T18:00:00-03:00",
    trilha: "Construção",
    tipo: "intervalo",
    materiais: [],
  },
  {
    id: "t422737",
    slug: "cerimonia-de-abertura",
    titulo: "Cerimônia de Abertura",
    descricao: "O Início da Nossa Jornada! O pontapé inicial do CITEC 2026! Junte-se a nós no Auditório Afya para conhecer os destaques da programação e se inspirar para os próximos dias de muito aprendizado, inovação e tecnologia na construção civil.",
    palestranteId: null,
    sala: "Auditório Afya",
    inicio: "2026-06-11T18:30:00-03:00",
    fim: "2026-06-11T19:00:00-03:00",
    trilha: "Construção",
    tipo: "institucional",
    materiais: [],
  },
  {
    id: "t422738",
    slug: "palestra-magna",
    titulo: "Palestra Magna",
    descricao: "Prepare-se para uma imersão no futuro da nossa profissão! Nesta palestra de destaque, vamos explorar como as inovações tecnológicas estão revolucionando o mercado e transformando a prática da engenharia. Uma oportunidade imperdível para expandir sua visão e descobrir as ferramentas que vão moldar os próximos passos da sua carreira.",
    palestranteId: null,
    sala: "Auditório Afya",
    inicio: "2026-06-11T19:00:00-03:00",
    fim: "2026-06-11T20:00:00-03:00",
    trilha: "Inovação",
    tipo: "palestra-magna",
    materiais: [],
  },
  {
    id: "t90001",
    slug: "encerramento-e-coffee-break-dia-1",
    titulo: "Encerramento e Coffee Break",
    descricao: "Encerramento do primeiro dia do CITEC 2026 com coffee break para networking entre os participantes.",
    palestranteId: null,
    sala: "Auditório Afya",
    inicio: "2026-06-11T20:00:00-03:00",
    fim: "2026-06-11T21:00:00-03:00",
    trilha: "Construção",
    tipo: "intervalo",
    materiais: [],
  },
  {
    id: "t422739",
    slug: "viabilidade-de-empreendimentos",
    titulo: "Viabilidade de Empreendimentos",
    descricao: "Chegou o momento de debatermos os rumos da nossa profissão. Junte-se a grandes nomes do mercado para uma troca de experiências franca e interativa. Uma conversa essencial para entender os desafios diários da construção civil por diferentes ângulos.",
    palestranteId: "p-igor-veras",
    palestrantesExtras: ["p-joao-ibiapino", "p-joefton-trindade"],
    sala: "Auditório Afya",
    inicio: "2026-06-12T14:00:00-03:00",
    fim: "2026-06-12T14:40:00-03:00",
    trilha: "Construção",
    tipo: "mesa-redonda",
    materiais: [],
  },
  {
    id: "t422740",
    slug: "aprovacao-e-licenciamentos-na-prefeitura",
    titulo: "Aprovação e Licenciamentos na Prefeitura",
    descricao: "Do projeto à execução: descubra como navegar pelos trâmites legais e processos da prefeitura. Aprenda os cuidados necessários para garantir aprovações mais ágeis e iniciar suas obras com o pé direito!",
    palestranteId: "p-jose-hamilton",
    sala: "Auditório Afya",
    inicio: "2026-06-12T15:00:00-03:00",
    fim: "2026-06-12T15:30:00-03:00",
    trilha: "Construção",
    tipo: "palestra",
    materiais: [],
  },
  {
    id: "t90002",
    slug: "intervalo-dia-2",
    titulo: "Intervalo",
    descricao: "Pausa para café e networking entre as palestras da tarde.",
    palestranteId: null,
    sala: "Auditório Afya",
    inicio: "2026-06-12T15:30:00-03:00",
    fim: "2026-06-12T16:00:00-03:00",
    trilha: "Construção",
    tipo: "intervalo",
    materiais: [],
  },
  {
    id: "t422741",
    slug: "responsabilidades-junto-ao-crea-pi",
    titulo: "Responsabilidades junto ao CREA-PI",
    descricao: "Da sala de aula para o mercado de trabalho! Descubra quais serão suas obrigações legais assim que se formar, como funciona a fiscalização e a importância do registro profissional para a valorização da sua carreira na engenharia piauiense.",
    palestranteId: "p-pedro-marques",
    sala: "Auditório Afya",
    inicio: "2026-06-12T16:00:00-03:00",
    fim: "2026-06-12T16:30:00-03:00",
    trilha: "Construção",
    tipo: "palestra",
    materiais: [],
  },
  {
    id: "t422742",
    slug: "gestao-de-equipes-e-equipamentos",
    titulo: "Gestão de Equipes e Equipamentos",
    descricao: "A obra vai muito além do projeto e dos cálculos! Aprenda as melhores práticas para liderar pessoas, otimizar o uso de maquinário e garantir alta produtividade no canteiro. Uma visão prática de como gerenciar recursos para entregar resultados com eficiência e dentro do prazo.",
    palestranteId: "p-emmanuel-fonseca",
    palestrantesExtras: ["p-leopoldo-melo", "p-mikelly-martins"],
    sala: "Auditório Afya",
    inicio: "2026-06-12T16:30:00-03:00",
    fim: "2026-06-12T17:10:00-03:00",
    trilha: "Construção",
    tipo: "mesa-redonda",
    materiais: [],
  },
  {
    id: "t422745",
    slug: "licitacao-e-contratos-na-engenharia-civil",
    titulo: "Licitação e Contratos na Engenharia Civil",
    descricao: "Navegue pelo universo das obras públicas e privadas. Conheça as principais leis, modalidades licitatórias e boas práticas na gestão de contratos para garantir a segurança jurídica e financeira dos projetos.",
    palestranteId: "p-joao-macedo",
    sala: "Sala G0-1",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422748",
    slug: "orcamentacao-de-obras",
    titulo: "Orçamentação de obras",
    descricao: "A base para a viabilidade e o lucro de qualquer projeto. Aprenda a levantar quantitativos, compor custos diretos e indiretos (BDI) e elaborar orçamentos competitivos e realistas.",
    palestranteId: "p-jorge-cerqueira",
    sala: "Laboratório de Informática 01",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422752",
    slug: "projetos-de-alvenaria-estrural",
    titulo: "Projetos de Alvenaria Estrural",
    descricao: "Racionalização e economia no canteiro. Aprenda os princípios de projeto e execução desse sistema construtivo altamente eficiente, desde a modulação das alvenarias até os cuidados essenciais na obra.",
    palestranteId: "p-wallison-medeiros",
    sala: "Sala G0-2",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422753",
    slug: "inteligencia-artificial-no-gerenciamento-de-obras",
    titulo: "Inteligência Artificial no Gerenciamento de Obras",
    descricao: "Do cronograma à entrega das chaves. Conheça as técnicas e ferramentas indispensáveis para planejar etapas, controlar prazos, alocar recursos e garantir que a execução siga exatamente o planejado.",
    palestranteId: "p-andrei-benicio",
    sala: "Sala G0-6",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422793",
    slug: "aprenda-python-criando-um-assistente-de-agenda-passo-a-passo",
    titulo: "Aprenda Python: Criando um assistente de agenda passo a passo.",
    descricao: "Mergulhe no mundo da programação de forma 100% prática e construa o seu próprio assistente virtual do absoluto zero! Neste minicurso, você dominará os fundamentos do Python enquanto cria uma ferramenta real para organizar o seu dia a dia.",
    palestranteId: "p-julio-marques",
    sala: "Laboratório de Informática 2",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422794",
    slug: "governanca-de-ti-e-solucoes-em-ambientes-multicloud",
    titulo: "Governança de TI e Soluções em Ambientes Multicloud",
    descricao: "Prepare-se para liderar a gestão estratégica da tecnologia e alinhar os objetivos de TI às metas do negócio em cenários altamente complexos. Neste minicurso, você aprenderá a orquestrar, proteger e otimizar recursos distribuídos entre múltiplos provedores de nuvem com total segurança.",
    palestranteId: "p-patricia-nogueira",
    sala: "Sala G0-7",
    inicio: "2026-06-13T08:30:00-03:00",
    fim: "2026-06-13T12:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422743",
    slug: "inspecao-de-estruturas-pos-incendio",
    titulo: "Inspeção de Estruturas Pós-incêndio",
    descricao: "Capacitação técnica para avaliar danos estruturais após sinistros. Aprenda metodologias para identificar patologias, avaliar a capacidade residual dos materiais e definir soluções seguras de recuperação.",
    palestranteId: "p-alisson-dias",
    sala: "Sala G0-1",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422744",
    slug: "fiscalizacao-de-obras-e-controle-de-medicoes",
    titulo: "Fiscalização de obras e controle de medições",
    descricao: "Domine a rotina de controle no canteiro. Entenda como acompanhar o cronograma físico-financeiro, atestar a qualidade da execução e realizar medições precisas para a liberação assertiva de recursos.",
    palestranteId: "p-itamo-miguel",
    sala: "Sala G0-2",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422749",
    slug: "introducao-ao-building-information-modeling",
    titulo: "Introdução ao Building Information Modeling",
    descricao: "Dê os primeiros passos no padrão mundial da construção. Entenda como a metodologia BIM revoluciona a modelagem de informações, a compatibilização de projetos e a gestão de todo o ciclo de vida da obra.",
    palestranteId: "p-paulo-roberto",
    sala: "Sala G0-6",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422750",
    slug: "drones-e-cameras-termais-na-engenharia-da-tecnologia-a-aplicacao-profissional",
    titulo: "Drones e Câmeras Termais na Engenharia: da Tecnologia à Aplicação Profissional",
    descricao: "A topografia e a inspeção na era digital. Descubra como a fotogrametria com drones e o uso de laser scanners estão acelerando a coleta de dados e trazendo precisão milimétrica aos levantamentos.",
    palestranteId: "p-matheus-barbosa",
    sala: "Sala G0-3",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422751",
    slug: "inteligencia-artificial-aplicada-a-projetos-de-engenharia",
    titulo: "Inteligência Artificial Aplicada a Projetos de Engenharia",
    descricao: "Explore o potencial das ferramentas de IA para revolucionar a sua produtividade. Veja como automatizar análises, otimizar planejamentos e gerar insights rápidos para a resolução de problemas complexos envolvendo projetos de engenharia.",
    palestranteId: "p-renan-gomes",
    sala: "Sala G0-5",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Tecnologia",
    tipo: "minicurso",
    materiais: [],
  },
  {
    id: "t422754",
    slug: "helice-continua-aplicada-a-fundacoes-e-contencoes-execucao-controle-e-casos-prat",
    titulo: "Hélice Continua Aplicada à Fundações e Contenções: Execução, Controle e Casos Práticos.",
    descricao: "Soluções modernas em fundações profundas. Aprofunde-se na tecnologia das estacas hélice contínua, compreendendo sua aplicabilidade, vantagens de execução e métodos de controle de qualidade no solo.",
    palestranteId: "p-fabrizio-feitosa",
    palestrantesExtras: ["p-fabricio-barros"],
    sala: "Sala G0-7",
    inicio: "2026-06-13T14:00:00-03:00",
    fim: "2026-06-13T16:00:00-03:00",
    trilha: "Construção",
    tipo: "minicurso",
    materiais: [],
  },
];

export const patrocinadores: Patrocinador[] = [
  // Diamante (3)
  { id: "s1",  nome: "LJ Engenharia",         logo: "/logos/sponsors/lj-engenharia.png", tier: "diamante", principal: true },
  { id: "s2",  nome: "Kalfix",                logo: "",                                  tier: "diamante" },
  { id: "s3",  nome: "Jopeli",                logo: "",                                  tier: "diamante" },
  // Patrocinadores (7) — antigo "ouro"
  { id: "s4",  nome: "Inspectum Engenharia",  logo: "/logos/sponsors/inspectum.png",     tier: "ouro" },
  { id: "s5",  nome: "Copperline",            logo: "/logos/sponsors/copperline.png",    tier: "ouro" },
  { id: "s6",  nome: "JCI Engenharia",        logo: "/logos/sponsors/jci.png",           tier: "ouro" },
  { id: "s7",  nome: "Construrappi",          logo: "/logos/sponsors/construrappi.png",  tier: "ouro" },
  { id: "s8",  nome: "MM Locações",           logo: "",                                  tier: "ouro" },
  { id: "s9",  nome: "Construtora Belvedere", logo: "",                                  tier: "ouro" },
  { id: "s10", nome: "Obratech",              logo: "",                                  tier: "ouro" },
  // Parceiros (7) — antigo "prata"
  { id: "s11", nome: "Jovem Engenheiro",      logo: "/logos/sponsors/jovem-engenheiro.png", tier: "prata" },
  { id: "s12", nome: "CREA Jr",               logo: "",                                  tier: "prata" },
  { id: "s13", nome: "CREA",                  logo: "/logos/sponsors/crea.png",          tier: "prata" },
  { id: "s14", nome: "VisionX",               logo: "/logos/sponsors/visionx.png",       tier: "prata" },
  { id: "s15", nome: "São José",              logo: "/logos/sponsors/sao-jose.png",      tier: "prata" },
  { id: "s16", nome: "David Brandão",         logo: "/logos/sponsors/david-brandao.png", tier: "prata" },
  { id: "s17", nome: "Expanserv",             logo: "/logos/sponsors/expanserv.png",     tier: "prata" },
];

export function getPalestrante(id: string | null) {
  if (!id) return undefined;
  return palestrantes.find((p) => p.id === id);
}

/** Retorna todos os palestrantes de uma palestra (principal + extras). */
export function getPalestrantesDePalestra(palestra: Palestra): Palestrante[] {
  const ids = [palestra.palestranteId, ...(palestra.palestrantesExtras ?? [])].filter(
    (x): x is string => Boolean(x),
  );
  return ids
    .map((id) => palestrantes.find((p) => p.id === id))
    .filter((p): p is Palestrante => Boolean(p));
}

export function getPalestraBySlug(slug: string) {
  return palestras.find((p) => p.slug === slug);
}

export function getPatrocinadorPrincipal() {
  return patrocinadores.find((p) => p.principal) ?? patrocinadores[0];
}
